name: Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  package:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - run: npm i
      - run: npm build
      - run: npm test
